# Generated by Django 4.2.2 on 2023-07-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=600)),
                ('product_img', models.ImageField(upload_to='Product_Img/')),
                ('product_name', models.CharField(max_length=200)),
                ('Product_building_year', models.DateTimeField()),
                ('Product_programingi_language', models.CharField(max_length=300)),
                ('Product_Addition_Programing_language', models.CharField(max_length=600)),
                ('product_summery', models.CharField(max_length=10000)),
                ('product_price', models.IntegerField()),
                ('dicount_product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wislist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_pannel.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=300)),
                ('order_id', models.CharField(max_length=300)),
                ('payment_signaure', models.CharField(max_length=3000)),
                ('shipping_address', models.CharField(max_length=300)),
                ('mobile_no', models.CharField(max_length=15)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_name', to='stu_pannel.product')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_pannel.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='default', max_length=100)),
                ('Phone_number', models.CharField(default='default', max_length=100)),
                ('email', models.CharField(default='default', max_length=100)),
                ('address', models.CharField(default='default', max_length=200)),
                ('pincode', models.IntegerField(default='default')),
                ('district', models.CharField(default='default', max_length=30)),
                ('photo_user', models.ImageField(upload_to='user_img')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_pannel.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
