# Generated by Django 4.2.2 on 2023-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
