# Generated by Django 4.2.2 on 2023-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0002_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Addition_Programing_language',
            field=models.CharField(default=56, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dicount_product_price',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
