# Generated by Django 4.2.2 on 2023-07-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0002_remove_order_product_id_remove_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default=8451, on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_name', to='stu_pannel.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(default=4512, on_delete=django.db.models.deletion.CASCADE, to='stu_pannel.product'),
            preserve_default=False,
        ),
    ]
