# Generated by Django 4.2.2 on 2023-07-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0003_product_product_addition_programing_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=600),
        ),
    ]
