# Generated by Django 4.2.2 on 2023-07-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0004_alter_order_product_id_alter_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
