# Generated by Django 4.2.2 on 2023-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0005_remove_order_product_id_remove_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(default=7885963, upload_to='product_data/'),
            preserve_default=False,
        ),
    ]
