# Generated by Django 4.2.2 on 2023-07-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0006_alter_extendeduser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='Phone_number',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='district',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='pincode',
            field=models.IntegerField(default='default'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
