# Generated by Django 4.2.2 on 2023-07-26 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stu_pannel', '0006_product_product_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_uname', models.CharField(max_length=600)),
                ('support_umno', models.IntegerField()),
                ('support_uemail', models.CharField(max_length=200)),
                ('support_proid', models.CharField(max_length=600)),
                ('support_uprodate', models.CharField(max_length=300)),
                ('support_uupid', models.CharField(max_length=6000)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
