# Generated by Django 4.2.2 on 2023-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_pannel', '0008_rename_support_supportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportuser',
            name='support_totalpayment',
            field=models.IntegerField(default=3810),
            preserve_default=False,
        ),
    ]
